### ISSUE TITLE
[Suggestion/Aide] Peut-on faire ce truc en json avec le module?

### ISSUE THREAD

**Issue by Mimexe** [Androz2091/easy-json-database#4]
Salut,
Comment peut-on faire ce truc en json avec le module?
```json
{
"bonjour": {
  "bonjour": "bonjour"
}
}
```
Si ce n'est pas possible vous pouvais ajouter cette fonctionnalité sur le module ?

**Comment by Androz2091** [comment]
Salut, c'est possible super simplement :
```js
db.set("bonjour", {
  "bonjour": "bonjour"
});

**Comment by Mimexe** [comment]
Merci ! Pour les futurs mise à jour pouvez vous mettre un moyen plus simple comme `bonjour.salut`

**Comment by Androz2091** [comment]
hmm why not ouaip je vais voir ça

**Comment by Androz2091** [comment]
C'est ajouté en v1.5.0
